name: Compile sillyGirl

on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 0 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Compile sillyGirl
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install Golang
        run: |
          wget https://dl.google.com/go/go1.16.8.linux-amd64.tar.gz
          tar -zxvf go1.16.8.linux-amd64.tar.gz
          mv go /usr/local/
          go version
