name: Compile and Release sillyGirl

on: [workflow_dispatch]
      
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Compile sillyGirl
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install Golang and Compile
        run: |
          wget -q https://dl.google.com/go/go1.16.8.linux-amd64.tar.gz
          tar -zxf go1.16.8.linux-amd64.tar.gz
          export GOROOT=$PWD/go
          export GOPATH=$PWD/gopath #GOPATH
          export PATH=$GOPATH/bin:$GOROOT/bin:
          go version
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o sillyGirl-linux-386
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -ldflags "-s -w" -o sillyGirl-linux-386-min
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o sillyGirl-linux-amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o sillyGirl-linux-amd64-min
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o sillyGirl-linux-arm
          CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags "-s -w" -o sillyGirl-linux-arm-min
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o sillyGirl-linux-arm64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o sillyGirl-linux-arm64-min
      - name: UPX
        run: |
          upx -9 sillyGirl-linux-386-min -o sillyGirl-linux-386-min-upx
          upx -9 sillyGirl-linux-amd64-min -o sillyGirl-linux-amd64-min-upx
          upx -9 sillyGirl-linux-arm-min -o sillyGirl-linux-arm-min-upx
          upx -9 sillyGirl-linux-arm64-min -o sillyGirl-linux-arm64-min-upx
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD-HH-mm
          utcOffset: "+08:00"
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v-${{ steps.current-time.outputs.formattedTime }}
          release_name: Release V-${{ steps.current-time.outputs.formattedTime }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./sillyGirl-linux-amd64
          asset_name: sillyGirl-linux-amd64
          asset_content_type: application/binarie
